name: Go

on:
  push:
    branches: [ development ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.4'  # The Go version to download (if necessary) and use.

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxcursor-dev libxrandr-dev libxinerama-dev


    - name: Build
      run: go build -v ./...
